### ISSUE TITLE
There is an exception when user closes WalletConnect dialog with QR-code

### ISSUE THREAD

**Issue by Lizusha** [Web3Modal/web3modal#121]
Here is my code:
`web3Connect.connect().
then(provider => { resolve(provider) }).
catch(err =>{
	reject(err)
})`

If user closes WalletConnect dialog with QR-code without scannig I receive exception:
"Unhandled Rejection (Error): User closed WalletConnect modal"

```
  300 | .then(() => {
  301 |   if (this.qrcode) {
  302 |     WalletConnectQRCodeModal.open(wc.uri, () => {
*> 303 |       reject(new Error('User closed WalletConnect modal'))
      | ^  304 |     })
  305 |   }
  306 |   wc.on('connect', (error, payload) => {
```

And this exception appears on browser screen, `catch` does not catch it.

**Comment by Velenir** [comment]
I believe this is the same issue as #38 
That one may have been closed prematurely

**Comment by pedrouid** [comment]
This needs to be fixed on the WalletConnect side, please open an issue here:
https://github.com/walletconnect/walletconnect-monorepo
