### ISSUE TITLE
QR-code scanning does not work for iOS (WalletConnect-compatible) apps

### ISSUE THREAD

**Issue by svetlanama** [Web3Modal/web3modal#125]
Hello, I see an issue during QR  scanning process when I'm trying  (WalletConnect-compatible) apps
such as: Gnosis Safe, Pillar, Trust. 

![wallet-connect](https://user-images.githubusercontent.com/1378991/75999612-2946b480-5f0b-11ea-8a4c-5fbb9dd596ca.jpeg)

**Comment by pedrouid** [comment]
Hi @svetlanama, the qr code you are scanning is a WalletConnect URI but the app is asking for a private key

**Comment by svetlanama** [comment]
Hi @pedrouid  could take a look a these screen also. I used Gnosis Safe


![File](https://user-images.githubusercontent.com/1378991/76517194-8a1f4100-6465-11ea-8923-b19cc98f7e4b.jpg)

**Comment by pedrouid** [comment]
Are you using the WalletConnect QR Code scanner? I just tried Gnosis Safe v1.13.1 on iOS and it worked.

Pinging @dmitrybespalov and @rmeissner to help you with this

**Comment by svetlanama** [comment]
Hi @pedrouid Sorry for long response
Gnosis Safe v1.13.1
iOS 13.4

**Comment by svetlanama** [comment]
@pedrouid  here is an example which I've tried to scan 
https://indra.connext.network/settings 
To see QR -> click activate wallet connect

**Comment by DmitryBespalov** [comment]
Hi @svetlanama, I've tried to connect with a safe, it connected successfully

**Comment by skerjancesheri-del** [comment]
RFC6238 TOTP
