### ISSUE TITLE
Overriding injected web3 provider information

### ISSUE THREAD

**Issue by hshar7** [Web3Modal/web3modal#126]
Is it possible to override the injected web3 provider logo and name in the modal? I'd like to be Metamask logo and say Metamask instead of Web3.

**Comment by pedrouid** [comment]
What are the conditions that you are getting Web3 logo instead of Metamask?

The simple check is that either `window.web3` or `window.ethereum` have a property for `isMetamask`. If this is not present then it shouldn't be labelled as Metamask.

**Comment by hshar7** [comment]
This is for users that do not have a web3 enabled browser. Is it possible to make the web3 option a redirect to download Metamask extension?

**Comment by pedrouid** [comment]
I see this is related to #57 which hasnt been fixed yet.

I like the download suggestion, I will create a different issue for it

**Comment by pedrouid** [comment]
Check custom provider display options

Fixed on [v1.5.0](https://github.com/Web3Modal/web3modal/releases/tag/1.5.0)
