### ISSUE TITLE
can't run torus against rinkeby

### ISSUE THREAD

**Issue by dkent600** [Web3Modal/web3modal#130]
Using:
* [Torus](https://github.com/torusresearch/torus-embed) v1.2.3.
* WebModal v1.1.0

Given the documentation on the Torus website, I would expect the following to result in a web3 connection to rinkeby.  But what actually results is a connection to main.

```
const web3Modal = new Web3Modal({
  providerOptions: {
   network: "rinkeby",
   torus: {
     package: Torus,
     options: {
       network: {
         host: "rinkeby",
         chainId: 4,
         networkName: "rinkeby",
       },
     },
   }
}
);

web3Modal.toggleModal();
```

The code causing the error appears to be here:

https://github.com/Web3Modal/web3modal/blob/dcb435e8805eb7c587a664bc2ea94f68d5332c4a/src/providers/connectors/torus.ts#L56

`opts.network.nodeUrl`, which is `unassigned`, ends up overwriting `network.host` which contains the value "rinkeby", thus changing "rinkeby" to `unassigned`.

**Comment by dkent600** [comment]
Honestly I find the Torus documentation a bit confusing as to what the `host` property is supposed to contain.

But this does work, though it is not documented on your readme.  I am wondering whether this is intentional or not:

```
  options: { network: "rinkeby" },
```

**Comment by dkent600** [comment]
Forgive me for throwing in a dish from the kitchen sink:  Another odd bit of behavior is that after calling `provider.enable();` then `getProviderInfo(provider).name` contains "MetaMask".  I expect it to contain "Torus"

**Comment by pedrouid** [comment]
cc @chaitanyapotti

**Comment by chaitanyapotti** [comment]
We removed isMetamask=true. So, this can be closed now

**Comment by dkent600** [comment]
Confirmed fixed
