### ISSUE TITLE
Torus gives wrong provider name

### ISSUE THREAD

**Issue by dkent600** [Web3Modal/web3modal#137]
Originally described here:  https://github.com/Web3Modal/web3modal/issues/130#issuecomment-602942907

When connecting using Torus, after calling `provider.enable()` then `getProviderInfo(provider).name` contains "MetaMask". I expect it to contain "Torus" or something.

**Comment by chaitanyapotti** [comment]
This can be closed too right.! @dkent600

**Comment by dkent600** [comment]
@chaitanyapotti This is not fixed by v1.3.0

**Comment by dkent600** [comment]
Yes, this was fixed by v1.3.0
