### ISSUE TITLE
Torus `provider.enable` never returns

### ISSUE THREAD

**Issue by dkent600** [Web3Modal/web3modal#138]
Torus `provider.enable` never returns.

**STEPS**
1. navigate _in new browser instance_ to here: https://alchemy.daostack.io/
2. if you've logged into this site before using a different provider, then log out:

![image](https://user-images.githubusercontent.com/1821666/78378112-84b5a200-759e-11ea-8d8f-05023e960c07.png)

3. click "Log in"

![image](https://user-images.githubusercontent.com/1821666/78378165-99923580-759e-11ea-9427-ce753093d39b.png)

4. The Web3Modal will appear.  Select Torus and authenticate yourself (I am using Google).  The Web3Modal will disappear.

**RESULT**
The "Log in" button is still showing.  `provider.enable` was invoked but never returns.

**EXPECT**
You should have been logged in.  `provider.enable` should have succeeded and returned.

![image](https://user-images.githubusercontent.com/1821666/78378662-4bc9fd00-759f-11ea-85f0-b7ed725d5d09.png)

5. Click "Log in" again

**RESULT**

Now you are logged in.  `provider.enable` was invoked and returned like it should.

**Comment by dkent600** [comment]
Here is the call to `provider.enable()`, in a function that shows the context of how everything is happening.

https://github.com/daostack/alchemy/blob/09caac7f7ac73deac9622baa3d62d4b16ce1f7b5/src/arc.ts#L396

**Comment by pedrouid** [comment]
Hey @chaitanyapotti, is there any check that needs to be made for logging before resolving the provider.enable?

**Comment by chaitanyapotti** [comment]
Seems to be an issue on our end. We'll be releasing a new version by the end of this week.
Sorry for the delay in response.

**Comment by chaitanyapotti** [comment]
we just released a new version v1.3.0.
Pls update, test and let us know if this can be closed

**Comment by dkent600** [comment]
v1.3.0 does not fix this problem

**Comment by dkent600** [comment]
@chaitanyapotti v1.3.0 of torus-embed *does* fix this problem, thanks!
