### ISSUE TITLE
Cannot display other options than Metamask

### ISSUE THREAD

**Issue by kohshiba** [Web3Modal/web3modal#140]
Hi, I'm struggling to implement web3modal.
I referred to example codes.
The issues are ..

1) When not logged in to Metamask
->Cannot go through web3Modal.connect() and provider option doesn't show up.

2)When logged in to Metamask
->meamask is automatically selected as a provider.

What should I deal with this?

**Comment by miohtama** [comment]
I added a new example application, hope this helps:

https://github.com/Web3Modal/web3modal-vanilla-js-example

**Comment by miohtama** [comment]
@kohshiba Any updates on this one? Please let me know if the issue still persists and we can provide guidance. If not please let us close the issue.

**Comment by kohshiba** [comment]
Thank you for sharing your example!
I used it as a reference and it was successfully resolved!
