### ISSUE TITLE
Unsticking a cached provider

### ISSUE THREAD

**Issue by miohtama** [Web3Modal/web3modal#143]
If any wallet provider gets cached, there is no application way to cleanly disconnect this. 

Reasons to get cached might be

* User just wants to change wallets

* Serving different application in the same localhost development URL

* Setting `cacheProvider` to true, but later regretting this

Currently, I am working around it like this, but a cleaner API might be needed:

https://github.com/Web3Modal/web3modal-vanilla-js-example/blob/master/example.js#L161

**Comment by pedrouid** [comment]
Looking at your example, you are not necessarily disabling the ability to cache a provider but clearing the cached provider.

This can be done already with `clearCachedProvider` method on the API

**Comment by miohtama** [comment]
@pedrouid excellent. Leaving this issue open until updating this example.

**Comment by crisgarner** [comment]
I already created a sign-out button for a few projects, if you need I can update de example really quick

**Comment by miohtama** [comment]
Example updated: https://github.com/Web3Modal/web3modal-vanilla-js-example/blob/master/example.js#L178
