### ISSUE TITLE
Wrong type expected for disableInjectedProvider

### ISSUE THREAD

**Issue by rmeissner** [Web3Modal/web3modal#144]
`disableInjectedProvider` is expected to be `{ package: any; options: any; }` but it should probably be a `boolean`

It is used here https://github.com/Web3Modal/web3modal/blob/master/src/core/controllers/providers.ts#L77 and the type is defined here https://github.com/Web3Modal/web3modal/blob/master/src/helpers/types.ts#L39

**Comment by pedrouid** [comment]
Fixed on [v1.6.0](https://github.com/Web3Modal/web3modal/releases/tag/1.6.0)
