### ISSUE TITLE
Configuring options when using local json-rpc (Ganache)

### ISSUE THREAD

**Issue by j-mars** [Web3Modal/web3modal#147]
How do you configure the options for each provider when using ganache?
The json notation for options is not clear on that aspect.

Thanks

**Edit -** Adding example for how I would do on Torus:
```typescript
const torus = new Torus();
await torus.init({
    network: {
        host: "https://localhost:8545"
     },
});
await torus.login(); // await torus.ethereum.enable();
const web3 = new Web3(torus.provider);
```

How to reproduce these options in web3modal?

**Comment by pedrouid** [comment]
You can add as `network` to providerOptions, example:

```typescript
import Web3 from "web3";
import Web3Modal from "web3modal";

const providerOptions = {
  /* See Provider Options Section */
};

const web3Modal = new Web3Modal({
  providerOptions: {
    torus: {
      package: Torus, // required
      options: {
        network: "https://localhost:8545"
       }
    }
  }
});

const provider = await web3Modal.connect();

const web3 = new Web3(provider);
```

**Comment by pedrouid** [comment]
This should actually be improved to allow for a full config object to be passed, I will keep this issue open until fixed

**Comment by j-mars** [comment]
Yes, that would be great. It would be also interesting to see in your Readme how to pass the local rpc option for all the providers, and not just Torus, as in many cases I believe developers use local testing environments.

Thanks for the great work 👍

**Comment by pedrouid** [comment]
Definitely, I will keep this issue updated

**Comment by j-mars** [comment]
@pedrouid I have noticed that by setting network as you mentioned, Torus connects fine and I can set web3, but then, when checking the current provider, the network ID (which sets itself to the default of 1) does not match the network ID of ganache (another number set by me)

There should be a way to set the id in the options object, I read in Torus docs and it is mentioned as 'chainID', but that does not seem work in web3modal as it keeps seting the id to 1, and not what I specified.

**Comment by pedrouid** [comment]
Fixed on [v1.6.0](https://github.com/Web3Modal/web3modal/releases/tag/1.6.0)

**Comment by pedrouid** [comment]
Hey @j-mars, check the README for how to configure for local networks, example: 

```js
const providerOptions = {
  torus: {
    package: Torus, // required
    options: {
      networkParams: {
        host: "https://localhost:8545", // optional
        chainId: 1337, // optional
        networkId: 1337 // optional
      },
      config: {
        buildEnv: "development" // optional
      }
    }
  }
};
```

**Comment by j-mars** [comment]
Thanks!
