### ISSUE TITLE
Proper means of logging out from a provider

### ISSUE THREAD

**Issue by j-mars** [Web3Modal/web3modal#151]
When trying to logout from a provider the following error appears, example for Portis:

`await provider._portis.logout() `

returns:
'index.js:1 TypeError: Cannot read property 'widget' of null at index.js:22 '

The means to force a logout would be to clear Portis local storage:
![image](https://user-images.githubusercontent.com/45543880/80389796-7a3baf00-88a3-11ea-9c84-7539644c65d6.png)

Is this the intended way to logout a user?

Example for fortmatic (also gives an error):

`await provider.fm.user.logout()` 

TypeError: Cannot read property 'sdk' of null at t.logout (fortmatic.js:1)

EDIT: as an added comment, it would be nice to have a standardized function to logout from any of the current selected provider. e.g. provider.logout()

**Comment by pedrouid** [comment]
Hi @j-mars, glad that you are able to fix it so quickly. 

There isn’t exactly a standardized method for disconnecting a provider.

I’m the maintainer of WalletConnect provider so I’ve included the close() method

Fortunately EIP-1193 has introduced the method disconnect() as requested by me and it’s close to being finalized. Hopefully this will become standardized across Etheruem providers
