### ISSUE TITLE
Possible to test wallet connect with web3modal on a local json-rpc?

### ISSUE THREAD

**Issue by j-mars** [Web3Modal/web3modal#152]
According to your docs in https://docs.walletconnect.org/quick-start/dapps/web3-provider
to pass a custom RPC url you do:

`
const provider = new WalletConnectProvider({
 rpc: {
  1: "https://mainnet.mycustomnode.com", 
  3: "https://ropsten.mycustomnode.com",
  100: "https://dai.poa.network"
 }
});
`
so infuraId is not mandatory in this case

I tried to replicate this in web3modal, but walletconnect does not appear in the modal because I didn't specify the infuraId (which shouldn't be mandatory if you specify an rpc instead)

`
walletconnect: {
package: WalletConnectProvider,
options: {
CHAIN_ID: LOCAL_HTTPS_ENDPOINT
}
},
`

Other way to go around without using an infuraId in this case?

**Comment by miohtama** [comment]
Currently there is an underlying issue that needs to be fixed

https://github.com/Web3Modal/web3modal/issues/154

If you use WalletConnect directly it works.

**Comment by pedrouid** [comment]
Fixed on [v1.6.0](https://github.com/Web3Modal/web3modal/releases/tag/1.6.0)

**Comment by R-Santev** [comment]
When I try to set ```1337: "http://localhost:8545"``` as a ```rpc``` property, it throws this error
![unknown](https://user-images.githubusercontent.com/77731162/150953744-4ae9b8cd-f3d1-4fb3-8530-aa6058bf739c.png)
