### ISSUE TITLE
WalletConnect provider is hardcoded to use Infura

### ISSUE THREAD

**Issue by miohtama** [Web3Modal/web3modal#154]
Currently it is impossible to pass `rpc` option argument to WalletConnect, because of 

https://github.com/Web3Modal/web3modal/blob/master/src/providers/providers/index.ts#L29

**Comment by pedrouid** [comment]
Just worked on a fix on this locally, going to publish it soon

**Comment by pedrouid** [comment]
Fixed on [v1.6.0](https://github.com/Web3Modal/web3modal/releases/tag/1.6.0)
