### ISSUE TITLE
Torus wallet is not returned when refreshing broswer

### ISSUE THREAD

**Issue by superdev1994** [Web3Modal/web3modal#170]
I am expecting wallet logged in with my google account but it pop-ups Torus window.

I think we can add Torus object to global(eg: window.web3Torus) and check if we were logged in using Torus,

I checked Torus main website and it works perfectly.

**Comment by chaitanyapotti** [comment]
@superdev1994 which version of torus and web3modal are you using?

**Comment by superdev1994** [comment]
@chaitanyapotti Thanks for your message. After the discussion with the Torus team, we updated the Torus version to the latest and it solved all problems. Happy coding! 😀
