### ISSUE TITLE
Please provide us a way to allow us to not make metamask popup when users come to the site.

### ISSUE THREAD

**Issue by owocki** [Web3Modal/web3modal#179]
i get the “metamask connect upon site popup” complaint like 2-3x a week.

Is there *any* way we can make it so that metamsk doesnt popup when the user, who has previously connected with web3modal/metamask, comes back to gitcoin?

our dev @octavioamu says "sadly is not so easy, seems there is not way to detect what wallet provider is conected without using the cached provider"

**Comment by owocki** [comment]
@pedrouid is there an easy way to do this using the current API?  @octavioamu has the details of our existing integration

**Comment by octavioamu** [comment]
- the flow to replicate it is connect metamask with gitcoin
- close browser 
- reopen browser
- as we use cacheprovider the wallet try to connect to metamask
- Metamask will prompt the login screen.

**Comment by owocki** [comment]
@octavioamu what is the code that executes "as we use cacheprovider the wallet try to reconnect to metamask" in our site? i want to poke at it.

if @pedrouid thinks there is no formal way to do this using web3modal, then i propose we hack something using localstorage to remember that the user is on metamask + not attempt to connect until they hit a web3 part of the site

**Comment by owocki** [comment]
> @octavioamu what is the code that executes "as we use cacheprovider the wallet try to reconnect to metamask" in our site? i want to poke at it.

@octavioamu bump on this ^^

**Comment by octavioamu** [comment]
@owocki you can check the main code here https://github.com/gitcoinco/web/blob/24f50e251609719f0a8caad2b4962f3d012ade83/app/assets/v2/js/wallet.js
but also each product check the cacheprovider to know if the user is already connected and then if the page need the wallet then ask about it if cacheprovider is not set.

**Comment by owocki** [comment]
thanks seems like we may want to wrap this code in some special casing with localstorage keys https://github.com/gitcoinco/web/blob/24f50e251609719f0a8caad2b4962f3d012ade83/app/assets/v2/js/wallet.js#L44-L49

**Comment by octavioamu** [comment]
Not sure I get what you mean but that is just the setup of wallet not actually what trigger the modal.  web3Modal.connect() is what trigger the modal. 
You can check here the flags https://github.com/Web3Modal/web3modal#optional-flags

**Comment by pedrouid** [comment]
Me and @octavioamu looked into this a few months back and I attempted to refactor the Web3Modal considerably to fit a better pattern to allow consistent check across providers but it ended up more complicated than expected (#169)

So I guess the best approach would be to add a special case for Metamask on page load:
```js
window.addEventListener("load", async () => {
  if (web3Modal.cachedProvider) {
    try {
      if (web3Modal.cachedProvider === "metamask") {
        const accounts = await window.ethereum.request({ method: "eth_accounts" });
        if (!accounts.length) {
          throw new Error("Metamask is not enabled");
        }
      }
      provider = await web3Modal.connect();
    } catch (e) {
      console.log("Could not get a wallet connection", e);
      return;
    }
  }
});
```
So basically if the cached provider is Metamask then check that accounts are exposed before calling connect on the Web3Modal

**Comment by octavioamu** [comment]
yes the problem I see is actually on chrome metamask web3Modal.cachedProvider is 'injected' not 'metamask'

**Comment by pedrouid** [comment]
Sorry my bad, I meant `injected` instead of `metamask`.

But in case you want to be more thorough and target Metamask specifically then you can do the following:

```js
import { getInjectedProviderName } from "web3modal"

window.addEventListener("load", async () => {
  if (web3Modal.cachedProvider) {
    try {
      if (web3Modal.cachedProvider === "injected" && getInjectedProviderName() === "metamask") {
        const accounts = await window.ethereum.request({ method: "eth_accounts" });
        if (!accounts.length) {
          throw new Error("Metamask is not enabled");
        }
      }
      provider = await web3Modal.connect();
    } catch (e) {
      console.log("Could not get a wallet connection", e);
      return;
    }
  }
});
```

**Comment by octavioamu** [comment]
cool I will make some tests, thanks @pedrouid

**Comment by octavioamu** [comment]
is there a way @pedrouid to access getInjectedProviderName from the js bundle ?

**Comment by octavioamu** [comment]
Is done!!! Thanks a lot @pedrouid I think this can be closed
