### ISSUE TITLE
Issue about connecting with WalletConnect on example

### ISSUE THREAD

**Issue by llp0574** [Web3Modal/web3modal#193]
Hi team,

I just tried to run the example on my local env, and then use IMToken to scan the QRcode showed by clicking the WalletConnect, but at last I just got an error which is showing below:

![image](https://user-images.githubusercontent.com/6203602/94316022-31a13280-ffb6-11ea-9ec0-46cba91205a9.png)

Please suggest me a possible solution about this issue and please let me know what else code you want me to provide, thanks!

BTW, I have tried using different infuraId to init Web3, but got same error, even if I used the id from your live demo site

**Comment by nizarrahmat** [comment]
go same error here..

**Comment by llp0574** [comment]
Solution is here, it's a bug caused by web3@1.3.0
https://ethereum.stackexchange.com/questions/87872/issue-about-connecting-with-walletconnect-by-using-the-example-of-web3modal
