### ISSUE TITLE
Metamask breaking changes are not supported

### ISSUE THREAD

**Issue by RiccardoBiosas** [Web3Modal/web3modal#206]
As of November 16th metamask has been rolling out breaking changes to their API which deprecate a lot of the methods injected into window.ethereum.
One of those methods is ethereum.enable() which is currently being used here:
https://github.com/Web3Modal/web3modal/blob/master/src/providers/connectors/injected.ts#L6
in order to initialize the injected provider.
It should be replaced with ```ethereum.request({ method: 'eth_requestAccounts' })```

**Comment by pedrouid** [comment]
Thanks for tackling this! I've included this fix with v1.9.2 release
