### ISSUE TITLE
Support for Gnosis Safe

### ISSUE THREAD

**Issue by Huanzhang89** [Web3Modal/web3modal#211]
I saw that in the readme Gnosis Safe is supported, is there somewhere I can find an example of that? I can't see to find the Gnosis Safe provider options anywhere.

**Comment by pedrouid** [comment]
Aren't they referring to WalletConnect provider??

**Comment by Huanzhang89** [comment]
Sorry yeah just did some more research and realised Gnosis Safe are going down the Wallet Connect route
