### ISSUE TITLE
Throws error when clicked outside web3modal

### ISSUE THREAD

**Issue by aditim121** [Web3Modal/web3modal#258]
When user clicks outside the web3modal, it throws error: **Modal closed by user**

Is there any way to do nothing when user clicks outside ?

**Comment by aditim121** [comment]
Got the answer. Closing this.

On onHide just make the modal set to true.

**Comment by loekTheDreamer** [comment]
how do you do that?

**Comment by loekTheDreamer** [comment]
> Got the answer. Closing this.
> 
> On onHide just make the modal set to true.

How do you do that?
