### ISSUE TITLE
web3modal not working on bsc trustwallet

### ISSUE THREAD

**Issue by Xh0st** [Web3Modal/web3modal#295]
Hello, Can you please help me with a problem??
I have setup web3modal vanilla javascript  and on metamask is working but on trustwallet or safepall it's not working
 
 const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
      rpc: {
         56: 'https://bsc-dataseed.binance.org/'
      },
      network: 'mainnet',
    }
  }
};

  web3Modal = new Web3Modal({
    cacheProvider: true, // optional
    providerOptions, // required
    disableInjectedProvider: false, // optional. For MetaMask / Brave / Opera.
  });

  console.log("Web3Modal instance is", web3Modal);
}

  console.log("Opening a dialog", web3Modal);
  try {
    provider = await web3Modal.connect();
    web3 = new Web3(provider);
  } catch(e) {
    console.log("Could not get a wallet connection", e);
    return;
  }

ERROR 
POST https://mainnet.infura.io/v3/ 401
POST https://mainnet.infura.io/v3/ 401

**Comment by Silur** [comment]
any news on this?

**Comment by Silur** [comment]
the solution for me was to add the "network: 'binance'" field to the providerOptions.options field:
```javascript
const providerOptions = {
  walletconnect: {
    package: WalletConnectProvider,
    options: {
    network: "binance", // here
    rpc: {
      56: 'https://bsc-dataseed.binance.org/'
    },
  network: 'mainnet',
  }
}
};
```

**Comment by Silur** [comment]
relevant code line for deciding the walletConnect chainId is [here](https://github.com/Web3Modal/web3modal/blob/master/src/providers/connectors/walletconnect.ts#L29)
