### ISSUE TITLE
Always have to connect again after page refresh

### ISSUE THREAD

**Issue by jasrajput** [Web3Modal/web3modal#388]
Hi,
Here's the flow:
  User Visit the website
  Clicked on the connect button
  Web3 Modal pops up and everything work fine

I was able to connect with web3 modal but there is one problem that whenever the page gets refresh it shows the connect button again and I had to click on the connect button in order to connect again.It just doesn't ask for re-confirmation on which provider to connect.It just connect automatically.This is the scenario after page got refresh.

I'm using Vanilla JS for web3 connectivity.is their any way reconnect without having to click connect button again and again

    `window.addEventListener('load', async () => {
          init();
          document.querySelector(".connect_wallet").addEventListener("click", onConnect);
     });

     async function onConnect() {
       try {
          provider = await web3Modal.connect();
       } catch (e) {
           console.log(e)
           return;
     }

     provider.on("accountsChanged", (accounts) => {
          fetchAccountData();
         });
      }

     async function fetchAccountData() {
        const web3 = new Web3(provider);
        const accounts = await web3.eth.getAccounts();
        $(".connect_wallet").hide();
     }

    function init() {

     if (location.protocol !== 'http:') {
         showErrorMessage("Only https allowed");
        document.querySelector(".connect_wallet").setAttribute("disabled", "disabled")
        return;
     }

    const providerOptions = {
        walletconnect: {
            package: WalletConnectProvider,
            options: {
                infuraId: INFURA_KEY,
            },
        },

        fortmatic: {
            package: Fortmatic,
            options: {
                key: FORMATIC_KEY 
            }
        }
    };

    web3Modal = new Web3Modal({
        theme: "dark",
        network: "mainnet",
        cacheProvider: true, // optional
        providerOptions, // required
        disableInjectedProvider: false, // optional. For MetaMask / Brave / Opera.
       });
    }`

**Comment by samparmenter** [comment]
What does your init function do?

After load you should be checking web3Modal.cached provider and running onConnect if its true. Something akin to.

`if (web3Modal.cachedProvider) onConnect()`

**Comment by jasrajput** [comment]
@samparmenter  hey, I've edit the code with init function.can you please check it out.

**Comment by samparmenter** [comment]
After you have called `new web3Modal` you need to then call `onConnect` if there is a cached provider on the web3Modal.

i.e.

```
web3Modal = new Web3Modal({
    theme: "dark",
    network: "mainnet",
    cacheProvider: true, // optional
    providerOptions, // required
    disableInjectedProvider: false, // optional. For MetaMask / Brave / Opera.
   });

if (web3Modal.cachedProvider) onConnect();
```

That should ensure that the connection from your previous page load is persisted. I'm not convinced that your https check is correct either if you are trying to ensure that it disables the button without a secure connection.

**Comment by jasrajput** [comment]
@samparmenter  OMG!! Thank you so much.. It works..Yea I was using on localhost at that time.
