### ISSUE TITLE
Is there a way to catch the "User Rejected" error?

### ISSUE THREAD

**Issue by ansonkao** [Web3Modal/web3modal#400]
See screenshot:

![image](https://user-images.githubusercontent.com/300092/151867963-206d2e39-1288-47d2-9bdb-cfa7433c5537.png)

I noticed that these exceptions are uncaught even in the example at https://web3modal.com/

I can't figure out how to catch the error and provide feedback to the user. I've tried:

```js
try {
  await (new Web3Modal({ ... })).connect()
} catch (e) {
  // Does not catch here!
}
```

Is there a way to handle it?

**Comment by yougotwill** [comment]
Hi @ansonkao, move the construction of the `Web3Modal` object outside of your try-catch and then run `connect()` inside of it. It catches correctly for me.

```
      const web3Modal = new Web3Modal({ ... });
      try {
        await web3Modal.connect();
      } catch (err) {
        console.error('Wallet connection failed. Reason:', err.message);
      }
```

**Comment by ansonkao** [comment]
That helps, thanks!
