### ISSUE TITLE
Torus throws an error `https.Agent` is not a constructor

### ISSUE THREAD

**Issue by T-Damer** [Web3Modal/web3modal#412]
- `node -v` is 17.3.0 (older versions throws same error)
- using `vite 2.8.4` with injected `windows` params and aliases for `process` (vite uses `import.env.meta.VITE_VAR` intead of `process.env`)

I've tried injecting `https.Agent` into the browser by myself — no success:
1. Added `<script type="module">https.Agent = new Agent()</script>` with different imports from `https`, `node:https`, even from `http`
2. Tried to add alias into the Vite config file 
3. I've tried different options, even without options:
```TS
    torus: {
      package: Torus,
    }
``` 
This issue is also [mentioned](https://github.com/nodejs/help/issues/3738) in the `node.js` lib. Maybe you can avoid using some options? Or maybe I can configure the `Torus` itself?

The stack trace is:
![image](https://user-images.githubusercontent.com/49658988/154813428-34a9ee26-1784-44d0-b131-9aa7bdf4996c.png)

**Comment by T-Damer** [comment]
Also mentioned here in the [web3](https://github.com/ChainSafe/web3.js/issues/4453) lib

**Comment by cielu** [comment]
你这问题解决了没，我也遇到了这问题，我感觉是react用ts出现的问题

**Comment by T-Damer** [comment]
> 你这问题解决了没，我也遇到了这问题，我感觉是react用ts出现的问题

Well, I didn't; we probably need to manually add the `Agent` (or its different version) in the web browser. Maybe we should take a look at [their dependencies](https://github.com/torusresearch/torus-embed/blob/develop/package.json)

**Comment by cielu** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/13715811/155879030-4a9f1cf5-3aa8-477c-8dea-6c943e816393.png">

**Comment by cielu** [comment]
@T-Damer  I got way to solved this problem , but I don't know if this is ok ;

<img width="570" alt="image" src="https://user-images.githubusercontent.com/13715811/155879580-ef549574-534f-4cf6-988d-fd75bee95385.png">

**Comment by cielu** [comment]
Or you can try 

```
import createAgent from 'agent-base';

......

    const options: HttpProviderOptions = {
      agent: {
        http: createAgent,
        https: createAgent,
      }
    }

```

tell me good way to solve this problem , thanks
