### ISSUE TITLE
Empty modal

### ISSUE THREAD

**Issue by Garito** [Web3Modal/web3modal#456]
Hi!
I have this code:
``` svelte
<script>
  import { onMount } from "svelte";
  import Web3 from "web3";
  import Web3Modal from "web3modal";

  import WalletConnectProvider from "@walletconnect/web3-provider";

  let web3Modal;
  let provider;
  let web3;

  const connect = async () => {
    provider = await web3Modal.connect();

    provider.on("accountsChanged", accounts => {
      console.log(accounts);
    });

    provider.on("chainChanged", chainId => {
      console.log(chainId);
    });

    provider.on("connect", info => {
      console.log(info);
    });

    provider.on("disconnect", error => {
      console.log(error);
    });

    web3 = new Web3(provider);
    console.log(await web3.eth.getGasPrice())
    web3.eth.getAccounts(console.log);
  }

  onMount(async () => {
    const providerOptions = {
      disableInjectedProvider: true,
      // cacheProvider: false,
      walletconnect: {
        package: WalletConnectProvider,
        options: {
          infuraId: "<THE INFURA PROJECT ID>",
        }
      },
      binancechainwallet: {
        package: true
      }
    };

    web3Modal = new Web3Modal(providerOptions)
  })
</script>

<button class={ $$props.class } on:click={ connect }><slot>Connect</slot></button>
{ web3 }
```
When the button is clicked, the opacity of the screen changes but the modal doesn't show
Looking at the html you can see this:
``` html
<div id="WEB3_CONNECT_MODAL_ID">
  <div class="sc-jRQBWg uYscM web3modal-modal-lightbox" offset="0" opacity="0.4">
    <div class="sc-gKclnd fmSSut web3modal-modal-container">
      <div class="sc-iCfMLu fFpYRP web3modal-modal-hitbox"></div>
      <div class="sc-furwcr dKfWpB web3modal-modal-card"></div>
    </div>
  </div>
</div>
```
Sorry if this is a newbie issue but I don't catch what is happening

Thanks

**Comment by gRoussac** [comment]
Hi, 

It seems that I reproduce the same issue when Metamask is not installed. If Metamask is already installed then popup appears. 

https://codesandbox.io/s/react-playground-forked-9jjix8

![Desktop-screenshot (2)](https://user-images.githubusercontent.com/3099551/162636608-e31a3632-94a1-4c86-aeea-c5e93047ae67.png)

Version 1.9.6

Cheers

**Comment by Garito** [comment]
In my case is already installed and the issue happens too

**Comment by YannSuissa** [comment]
I have the same issue when metamask is installed but not enabled, just an empty darker div

**Comment by Garito** [comment]
I've used disableInjectedProvider = true to avoid the automatic connection to metamask

**Comment by mikealeonetti** [comment]
I'm having the same issue as well. Was there a fix for this?

**Comment by Garito** [comment]
It does, thanks!

**Comment by YannSuissa** [comment]
The bug is still here, ex : 
[https://codesandbox.io/s/react-playground-forked-oo1wi8](https://codesandbox.io/s/react-playground-forked-oo1wi8)

**Comment by gRoussac** [comment]
@YannSuissa I believe it is not a bug but a missunderstanding about the purpose of this modal and we assumed what the doc does not say.

````
        const providerOptions = {
          /* See Provider Options Section */
        };
````

simply does not prodvide any provider. So if you don't have metamask, it will not provide a div into the modal proposing you to install metamask and so far I don't see any prodvider linked to Consensys actually. It is always supposely injected. 
https://github.com/WalletConnect/web3modal/tree/master/docs/providers

So far that I see this means that if the user has not metamask already installed, metamask will not be proposed in the modal unlike other providers apparently.

**Comment by Garito** [comment]
@YannSuissa the modal options go to the modal object not the connection function:
https://codesandbox.io/s/react-playground-forked-y8ikq3?file=/index.js
and like @gRoussac pointed out, you have defined no provider apart from metamask (which opens for me as expected)

**Comment by gRoussac** [comment]
@Garito Error excepted I see no difference with my code sandbox above. I belive we just missunderstood the example of the documentation.

If you don't have metamask installed, the modal is empty. While I was assuming the modal would at least propose the user to install Metamask.

your code sandbox without metamask installed.




![React-PlayGround-forked-CodeSandbox](https://user-images.githubusercontent.com/3099551/188508139-c2e5f2f8-eddd-4165-bcb7-955f18d0df3d.png)

Cheers thanks again for your work anyway.

**Comment by Garito** [comment]
Yep, no difference... nice to know, thanks
