### ISSUE TITLE
Conflict between Injected Web3 Providers

### ISSUE THREAD

**Issue by kyokosdream** [Web3Modal/web3modal#468]
If you have both Coinbase Wallet and Metamask Chrome extension, clicking on the Metamask option causes both extensions to prompt for account access. 

I believe this is a result of the Coinbase browser extension functioning as an injected Web3 provider, much like Metamask. There needs to be some kind of check in the code that prevents this from happening. Please advise. 

Happy to propose a pull request if we can get to the bottom of this.

**Comment by kyokosdream** [comment]
#374

**Comment by kyokosdream** [comment]
https://github.com/NoahZinsmeister/web3-react/issues/300

**Comment by kyokosdream** [comment]
Closing this issue since it's a duplicate and be fixed with @4skinskywalker approach to custom connectors.

**Comment by moondayli** [comment]
> Closing this issue since it's a duplicate and be fixed with @4skinSkywalker approach to custom connectors.

We're can I find the code snippet
