### ISSUE TITLE
UX issue when choosing WalletConnect without signing in mobile dapp browser

### ISSUE THREAD

**Issue by oznekenzo** [Web3Modal/web3modal#51]
if you choose walletconnect as a provider, then scan in your mobile dapp browser, but do not sign and hit cancel instead, every time you select walletconnect as a provider, it is using (or expecting to use) the signature from the mobile dapp browser that it never got in the first place.  so signing in to a dapp with wallet connect just waits forever.  there should be some way (I think?) where the user can restart this process so that it can finish correctly.
I think right now you have to clear application cache to start this process over.
I understand this is an edge case, and 3box won't need this to be finished for us to release, just something to think about!

**Comment by Velenir** [comment]
I believe this is a problem with stale data in `localStorage.walletconnect` (same as WalletConnect/walletconnect-monorepo#193).

That problem can be mitigated by closing websocket connection (`provider.close()`) when disconnecting from WalletConnect / switching to a different provider, as `localStorage.walletconnect` gets cleared on `provider.wc.on('disconnect', ) or provider.on('stop', )` event

**Comment by pedrouid** [comment]
Issue already reprorted on WalletConnect's monorepo

**Comment by snitm** [comment]
> Issue already reprorted on WalletConnect's monorepo

That isn't the right way to ensure problems get fixed.  This issue still exists and it is making web3modal's WalletConnect support useless (requires poweruser to go clear their browser's cache to cause WalletConnect QR to display again).

**Comment by snitm** [comment]
> > Issue already reprorted on WalletConnect's monorepo
> 
> That isn't the right way to ensure problems get fixed. This issue still exists and it is making web3modal's WalletConnect support useless (requires poweruser to go clear their browser's cache to cause WalletConnect QR to display again).

I hacked my dapp with this brute force disconnect (runs when user clicks "Disconnect Wallet"):

@@ -65,18 +67,22 @@ function useWeb3Modal(config = {}) {
        async function () {
            setSignedInAddress("");
            await web3Modal.clearCachedProvider();
+           if (provider.provider.wc) {
+               provider.provider.wc.killSession();
+               provider.provider.stop();
+           }
            window.location.reload();
        },
-       [web3Modal],
+       [web3Modal, provider],
     );
