### ISSUE TITLE
make IProviderInfo.check be a function rather than a string

### ISSUE THREAD

**Issue by dkent600** [Web3Modal/web3modal#56]
It would be potentially possible to identify more types of providers if `IProviderInfo.check` were a function rather than a string.  So like this:

```
type CheckProviderIdentity = (provider: any) => boolean;

export interface IProviderInfo {
  name: string;
  type: string;
  logo: string;
  check: CheckProviderIdentity;
  styled: {
    [prop: string]: any;
  };
}
```

Use it:

```
const providerInfo = {
    name: "WalletConnect",
    logo: WalletConnectLogo,
    type: "qrcode",
    check: (provider:any): boolean => !!provider["isWalletConnect"],
    styled: {
      noShadow: false
    }
  };

const isWalletConnect = providerInfo .check(aProvider);
```

It would be cool to be able use this pattern to identify a provider like Opera which doesn't lend itself to identification using the current Web3Connect `check`.  But theoretically a check _function_ could make this possible, though I must say, in the case of Opera I'm at pains to figure out how to do it using the provider itself, but one could check the browser like this:

```
const providerInfo = {
    name: "Opera",
    logo: someLogo,
    type: "injected",
    check: (_provider:any): boolean => (!!window.opr && !!opr.addons) || !!window.opera || navigator.userAgent.indexOf(' OPR/') >= 0,
    styled: {
      noShadow: false
    }
  };
```

**Comment by pedrouid** [comment]
Interesting.. I like this approach

**Comment by pedrouid** [comment]
I was able to detect Opera browser without requiring this change and keep the initial design of provider checks intact
