### ISSUE TITLE
Opera is listed as a supported injection, but doesn't work

### ISSUE THREAD

**Issue by dkent600** [Web3Modal/web3modal#57]
Opera is listed [here](https://github.com/web3connect/web3connect/blob/5e8c07e0c03f3e04d0aed7e888a05956cadd7e95/src/providers/index.ts#L109) as a supported injection, but doesn't work as there is no provider property named "isOpera".

**Comment by pedrouid** [comment]
Are you also getting this error message?
<img width="553" alt="Screenshot 2019-08-04 13 46 13" src="https://user-images.githubusercontent.com/10136079/62423846-4a69cd00-b6be-11e9-861f-6e840ba8e777.png">

**Comment by crisgarner** [comment]
This might be related to some updates in Opera, last time I checked their injected provider didn't work like the rest.

**Comment by crisgarner** [comment]
As a temporal fix right now it shows the default provider icon 

![Screenshot from 2019-08-24 12-30-29](https://user-images.githubusercontent.com/578688/63641413-19503d00-c66b-11e9-9cf7-0b75f96eab40.png)

**Comment by pedrouid** [comment]
Fixed on [v1.6.0](https://github.com/Web3Modal/web3modal/releases/tag/1.6.0)
