### ISSUE TITLE
No way to logout of Portis

### ISSUE THREAD

**Issue by nickgeoca** [Web3Modal/web3modal#80]
Portis has a `portis.logout()` function. But what is given is typically the provider, such as `portis.provider` instead of the portis variable. Or a logout feature built in.

**Comment by miguelmota** [comment]
you can do [`provider._portis.logout()` ](https://github.com/web3connect/web3connect/blob/f4e84f52c1dbc26daab0ca596b0f43a4c2d5ad6d/src/core/connectors/portis.ts#L31)

It'd be nice though to standardize around something like [`provider.disable()`](https://ethereum-magicians.org/t/window-ethereum-disable-for-logging-out-of-provider/3630)
